# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started', models.DateField()),
                ('finished', models.DateField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started', models.DateField()),
                ('finished', models.DateField(blank=True, null=True)),
                ('scheduled', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('position', models.IntegerField(choices=[(1, 'Manager'), (2, 'Designer'), (3, 'Clerk'), (4, 'Driver'), (5, 'Jobber'), (6, 'Miller'), (7, 'Fitter'), (8, 'Accountant'), (9, 'Sysop'), (10, 'writer')])),
                ('salary_period', models.CharField(choices=[('D', 'Day'), ('M', 'Month'), ('R', 'Payment by results')], max_length=1)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('starting', models.DateField()),
                ('fired', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='hold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Worker'),
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Worker'),
        ),
    ]
